const data = {
  vegetarian: false,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 19,
  gaps: 'no',
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 11,
  healthScore: 1,
  creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
  license: 'CC BY 3.0',
  sourceName: 'Foodista',
  pricePerServing: 103.5,
  extendedIngredients: [
    {
      id: 19314,
      aisle: 'Baking',
      image: 'cherry-pie-slice.jpg',
      consistency: 'SOLID',
      name: 'cherry pie filling',
      nameClean: 'cherry pie filling',
      original: '1 cup canned cherry pie filling',
      originalName: 'canned cherry pie filling',
      amount: 1,
      unit: 'cup',
      meta: ['canned'],
      measures: {
        us: {
          amount: 1,
          unitShort: 'cup',
          unitLong: 'cup',
        },
        metric: {
          amount: 236.588,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 19165,
      aisle: 'Baking',
      image: 'cocoa-powder.png',
      consistency: 'SOLID',
      name: 'cocoa powder',
      nameClean: 'cacao powder',
      original: '3 tablespoons Cocoa Powder (2 T.)',
      originalName: 'Cocoa Powder (2 T.)',
      amount: 3,
      unit: 'tablespoons',
      meta: ['(2 T.)'],
      measures: {
        us: {
          amount: 3,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
        metric: {
          amount: 3,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
      },
    },
    {
      id: 1017,
      aisle: 'Cheese',
      image: 'cream-cheese.jpg',
      consistency: 'SOLID',
      name: 'cream cheese',
      nameClean: 'cream cheese',
      original: '12 oz. (1 1/2 pkg.) cream cheese, softened',
      originalName: '12 oz. cream cheese, softened',
      amount: 1.5,
      unit: 'pkg',
      meta: ['softened'],
      measures: {
        us: {
          amount: 1.5,
          unitShort: 'pkg',
          unitLong: 'packages',
        },
        metric: {
          amount: 1.5,
          unitShort: 'pkg',
          unitLong: 'packages',
        },
      },
    },
    {
      id: 1123,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'egg.png',
      consistency: 'SOLID',
      name: 'eggs',
      nameClean: 'egg',
      original: '2 eggs',
      originalName: 'eggs',
      amount: 2,
      unit: '',
      meta: [],
      measures: {
        us: {
          amount: 2,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 2,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 19177,
      aisle: 'Baking',
      image: 'gelatin-powder.jpg',
      consistency: 'SOLID',
      name: 'gelatin',
      nameClean: 'gelatin',
      original: '1 t. gelatin',
      originalName: 'gelatin',
      amount: 1,
      unit: 't',
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
        metric: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
      },
    },
    {
      id: 1053,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'fluid-cream.jpg',
      consistency: 'LIQUID',
      name: 'heavy cream',
      nameClean: 'cream',
      original: '1 c. heavy cream, chilled',
      originalName: 'heavy cream, chilled',
      amount: 1,
      unit: 'c',
      meta: ['chilled'],
      measures: {
        us: {
          amount: 1,
          unitShort: 'cup',
          unitLong: 'cup',
        },
        metric: {
          amount: 236.588,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 10018166,
      aisle: 'Sweet Snacks',
      image: 'oreos.png',
      consistency: 'SOLID',
      name: 'oreo cookies',
      nameClean: 'oreo cookies',
      original: '12 Oreo cookies, crushed',
      originalName: 'Oreo cookies, crushed',
      amount: 12,
      unit: '',
      meta: ['crushed'],
      measures: {
        us: {
          amount: 12,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 12,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 19336,
      aisle: 'Baking',
      image: 'powdered-sugar.jpg',
      consistency: 'SOLID',
      name: 'powdered sugar',
      nameClean: 'powdered sugar',
      original: '2 T. powdered sugar',
      originalName: 'powdered sugar',
      amount: 2,
      unit: 'T',
      meta: [],
      measures: {
        us: {
          amount: 2,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
        metric: {
          amount: 2,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
      },
    },
    {
      id: 2047,
      aisle: 'Spices and Seasonings',
      image: 'salt.jpg',
      consistency: 'SOLID',
      name: 'salt',
      nameClean: 'table salt',
      original: '1 1/2 teaspoons Salt (1 tsp.)',
      originalName: '1/2 teaspoons Salt',
      amount: 1,
      unit: 'tsp',
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
        metric: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
      },
    },
    {
      id: 10019903,
      aisle: 'Baking',
      image: 'chocolate-chips.jpg',
      consistency: 'SOLID',
      name: 'semi sweet chocolate chips',
      nameClean: 'semisweet chocolate chips',
      original: '3/4 c. semi-sweet chocolate chips, melted and cooled slightly',
      originalName: 'semi-sweet chocolate chips, melted and cooled slightly',
      amount: 0.75,
      unit: 'c',
      meta: ['cooled', 'melted'],
      measures: {
        us: {
          amount: 0.75,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 177.441,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 1056,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'sour-cream.jpg',
      consistency: 'SOLID',
      name: 'sour cream',
      nameClean: 'sour cream',
      original: '1/4 c. sour cream',
      originalName: 'sour cream',
      amount: 0.25,
      unit: 'c',
      meta: ['sour'],
      measures: {
        us: {
          amount: 0.25,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 59.147,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 19335,
      aisle: 'Baking',
      image: 'sugar-in-bowl.png',
      consistency: 'SOLID',
      name: 'sugar',
      nameClean: 'sugar',
      original: '2/3 c. sugar',
      originalName: 'sugar',
      amount: 0.6666667,
      unit: 'c',
      meta: [],
      measures: {
        us: {
          amount: 0.667,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 157.725,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 1145,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'butter-sliced.jpg',
      consistency: 'SOLID',
      name: 'unsalted butter',
      nameClean: 'unsalted butter',
      original: '1 1/2 T. unsalted butter, melted',
      originalName: 'unsalted butter, melted',
      amount: 1.5,
      unit: 'T',
      meta: ['unsalted', 'melted'],
      measures: {
        us: {
          amount: 1.5,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
        metric: {
          amount: 1.5,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
      },
    },
    {
      id: 2050,
      aisle: 'Baking',
      image: 'vanilla-extract.jpg',
      consistency: 'LIQUID',
      name: 'vanilla extract',
      nameClean: 'vanilla extract',
      original: '1 t. vanilla extract',
      originalName: 'vanilla extract',
      amount: 1,
      unit: 't',
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
        metric: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
      },
    },
    {
      id: 14412,
      aisle: 'Beverages',
      image: 'water.png',
      consistency: 'LIQUID',
      name: 'water',
      nameClean: 'water',
      original: '1 1/8 cups Water (¾ C.)',
      originalName: '1/8 cups Water',
      amount: 0.75,
      unit: 'C',
      meta: [],
      measures: {
        us: {
          amount: 0.75,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 0.75,
          unitShort: 'cups',
          unitLong: 'cups',
        },
      },
    },
  ],
  id: 635113,
  title: 'Black Forest Mini Cheesecakes',
  readyInMinutes: 45,
  servings: 12,
  sourceUrl:
    'http://www.foodista.com/recipe/QPNQ6J7Y/black-forest-mini-cheesecakes',
  image: 'https://spoonacular.com/recipeImages/635113-556x370.jpg',
  imageType: 'jpg',
  summary:
    'This recipe serves 12 and costs $1.03 per serving. One serving contains <b>429 calories</b>, <b>5g of protein</b>, and <b>27g of fat</b>. This recipe is liked by 11 foodies and cooks. A mixture of powdered sugar, cocoa powder, gelatin, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 23%</b>. This score is rather bad. Try <a href="https://spoonacular.com/recipes/black-forest-mini-cheesecakes-50091">Black Forest Mini Cheesecakes</a>, <a href="https://spoonacular.com/recipes/mini-black-forest-cheesecakes-50081">Mini Black Forest Cheesecakes</a>, and <a href="https://spoonacular.com/recipes/mini-black-forest-cheesecakes-588835">Mini Black Forest Cheesecakes</a> for similar recipes.',
  cuisines: [],
  dishTypes: ['side dish'],
  diets: [],
  occasions: [],
  winePairing: {
    pairedWines: [],
    pairingText: '',
    productMatches: [],
  },
  instructions:
    "<ol><li>1. Preheat oven to 325 degrees. In a medium bowl, mix together crushed Oreos and melted butter. Line a standard sized muffin tin with paper liners. Add a heaping tablespoon of the cookie crumb mixture to each liner, press with the back of a spoon to form the crust. Bake for 5 minutes. Remove from the oven, set aside to cool while preparing the filling.</li><li>2. In a small bowl stir together sugar, cocoa powder and salt. In a large mixing bowl add soften cream cheese and sugar/cocoa mix. Beat with an electric mixer until smooth, add melted chocolate, heavy cream and sour cream, beat until combined. Add eggs, one at a time and mix well after each, then add in vanilla. Tap the bowl on the counter firmly a couple of times to release any air bubbles.</li><li>3. Divide batter between the cupcake liners (liners will be full). Tap the pan a couple of times to be sure there are no large air bubble. Bake for 15-20 minutes, until the centers jiggle just slightly. (Original recipe called for baking time of 17-20 minutes, mine were done at the 15 minute mark.) Remove pan from oven, let cool at room temp. for 1 hour. Cover in plastic wrap and refrigerate for 2 hours or until fully cooled before topping.</li><li>4. Top the cheesecakes: In a medium bowl whisk together heavy cream, powdered sugar and vanilla. Place the bowl in the refrigerator, along with the beaters from your mixer, for 10-15 minutes to get everything well chilled. Add gelatin to a small bowl, add water. When gelatin absorbs all the water microwave for about 10 seconds to heat and melt the gelatin and make it pourable. Set aside to cool a bit. Beat the cream until just before it reaches soft peak stage, check your gelatin to be sure it has cooled slightly but is still a pourable consistency (if it solidified, just pop it back in the microwave for a couple seconds). With the mixer running, slowly pour in the gelatin and finish whipping the cream to soft peak stage.</li><li>5. Top the cakes with a generous spoon full of the whipped cream, using the back of a spoon make a little nest indentation in the top for the cherry filling. Add a spoon full of the cherry filling and you're done.</li></ol>",
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'Preheat oven to 325 degrees. In a medium bowl, mix together crushed Oreos and melted butter. Line a standard sized muffin tin with paper liners.',
          ingredients: [
            {
              id: 1001,
              name: 'butter',
              localizedName: 'butter',
              image: 'butter-sliced.jpg',
            },
            {
              id: 10018166,
              name: 'oreo cookies',
              localizedName: 'oreo cookies',
              image: 'oreos.png',
            },
          ],
          equipment: [
            {
              id: 404671,
              name: 'muffin tray',
              localizedName: 'muffin tray',
              image: 'muffin-tray.jpg',
            },
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
        },
        {
          number: 2,
          step: 'Add a heaping tablespoon of the cookie crumb mixture to each liner, press with the back of a spoon to form the crust.',
          ingredients: [
            {
              id: 10118192,
              name: 'cookies',
              localizedName: 'cookies',
              image: 'shortbread-cookies.jpg',
            },
            {
              id: 0,
              name: 'crust',
              localizedName: 'crust',
              image: '',
            },
          ],
          equipment: [],
        },
        {
          number: 3,
          step: 'Bake for 5 minutes.',
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
          length: {
            number: 5,
            unit: 'minutes',
          },
        },
        {
          number: 4,
          step: 'Remove from the oven, set aside to cool while preparing the filling.',
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
        },
        {
          number: 5,
          step: 'In a small bowl stir together sugar, cocoa powder and salt. In a large mixing bowl add soften cream cheese and sugar/cocoa mix. Beat with an electric mixer until smooth, add melted chocolate, heavy cream and sour cream, beat until combined.',
          ingredients: [
            {
              id: 19165,
              name: 'cocoa powder',
              localizedName: 'cocoa powder',
              image: 'cocoa-powder.png',
            },
            {
              id: 1017,
              name: 'cream cheese',
              localizedName: 'cream cheese',
              image: 'cream-cheese.jpg',
            },
            {
              id: 1053,
              name: 'heavy cream',
              localizedName: 'heavy cream',
              image: 'fluid-cream.jpg',
            },
            {
              id: 1056,
              name: 'sour cream',
              localizedName: 'sour cream',
              image: 'sour-cream.jpg',
            },
            {
              id: 19081,
              name: 'chocolate',
              localizedName: 'chocolate',
              image: 'milk-chocolate.jpg',
            },
            {
              id: 19335,
              name: 'sugar',
              localizedName: 'sugar',
              image: 'sugar-in-bowl.png',
            },
            {
              id: 2047,
              name: 'salt',
              localizedName: 'salt',
              image: 'salt.jpg',
            },
          ],
          equipment: [
            {
              id: 404628,
              name: 'hand mixer',
              localizedName: 'hand mixer',
              image: 'hand-mixer.png',
            },
            {
              id: 405907,
              name: 'mixing bowl',
              localizedName: 'mixing bowl',
              image: 'mixing-bowl.jpg',
            },
          ],
        },
        {
          number: 6,
          step: 'Add eggs, one at a time and mix well after each, then add in vanilla. Tap the bowl on the counter firmly a couple of times to release any air bubbles.',
          ingredients: [
            {
              id: 1052050,
              name: 'vanilla',
              localizedName: 'vanilla',
              image: 'vanilla.jpg',
            },
            {
              id: 1123,
              name: 'egg',
              localizedName: 'egg',
              image: 'egg.png',
            },
          ],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
          ],
        },
        {
          number: 7,
          step: 'Divide batter between the cupcake liners (liners will be full). Tap the pan a couple of times to be sure there are no large air bubble.',
          ingredients: [
            {
              id: 18139,
              name: 'cupcakes',
              localizedName: 'cupcakes',
              image: 'plain-cupcake.jpg',
            },
          ],
          equipment: [
            {
              id: 404676,
              name: 'muffin liners',
              localizedName: 'muffin liners',
              image: 'muffin-or-cupcake-forms.png',
            },
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'pan.png',
            },
          ],
        },
        {
          number: 8,
          step: 'Bake for 15-20 minutes, until the centers jiggle just slightly. (Original recipe called for baking time of 17-20 minutes, mine were done at the 15 minute mark.)',
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
          length: {
            number: 55,
            unit: 'minutes',
          },
        },
        {
          number: 9,
          step: 'Remove pan from oven, let cool at room temp. for 1 hour. Cover in plastic wrap and refrigerate for 2 hours or until fully cooled before topping.',
          ingredients: [
            {
              id: 10018364,
              name: 'wrap',
              localizedName: 'wrap',
              image: 'flour-tortilla.jpg',
            },
          ],
          equipment: [
            {
              id: 404730,
              name: 'plastic wrap',
              localizedName: 'plastic wrap',
              image: 'plastic-wrap.jpg',
            },
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'pan.png',
            },
          ],
          length: {
            number: 180,
            unit: 'minutes',
          },
        },
        {
          number: 10,
          step: 'Top the cheesecakes: In a medium bowl whisk together heavy cream, powdered sugar and vanilla.',
          ingredients: [
            {
              id: 19336,
              name: 'powdered sugar',
              localizedName: 'powdered sugar',
              image: 'powdered-sugar.jpg',
            },
            {
              id: 1053,
              name: 'heavy cream',
              localizedName: 'heavy cream',
              image: 'fluid-cream.jpg',
            },
            {
              id: 1052050,
              name: 'vanilla',
              localizedName: 'vanilla',
              image: 'vanilla.jpg',
            },
          ],
          equipment: [
            {
              id: 404661,
              name: 'whisk',
              localizedName: 'whisk',
              image: 'whisk.png',
            },
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
          ],
        },
        {
          number: 11,
          step: 'Place the bowl in the refrigerator, along with the beaters from your mixer, for 10-15 minutes to get everything well chilled.',
          ingredients: [],
          equipment: [
            {
              id: 404726,
              name: 'blender',
              localizedName: 'blender',
              image: 'blender.png',
            },
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
          ],
          length: {
            number: 15,
            unit: 'minutes',
          },
        },
        {
          number: 12,
          step: 'Add gelatin to a small bowl, add water. When gelatin absorbs all the water microwave for about 10 seconds to heat and melt the gelatin and make it pourable. Set aside to cool a bit. Beat the cream until just before it reaches soft peak stage, check your gelatin to be sure it has cooled slightly but is still a pourable consistency (if it solidified, just pop it back in the microwave for a couple seconds). With the mixer running, slowly pour in the gelatin and finish whipping the cream to soft peak stage.',
          ingredients: [
            {
              id: 19177,
              name: 'gelatin',
              localizedName: 'gelatin',
              image: 'gelatin-powder.jpg',
            },
            {
              id: 1053,
              name: 'cream',
              localizedName: 'cream',
              image: 'fluid-cream.jpg',
            },
            {
              id: 14412,
              name: 'water',
              localizedName: 'water',
              image: 'water.png',
            },
            {
              id: 0,
              name: 'pop',
              localizedName: 'soft drink',
              image: '',
            },
          ],
          equipment: [
            {
              id: 404762,
              name: 'microwave',
              localizedName: 'microwave',
              image: 'microwave.jpg',
            },
            {
              id: 404726,
              name: 'blender',
              localizedName: 'blender',
              image: 'blender.png',
            },
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
          ],
        },
        {
          number: 13,
          step: 'Top the cakes with a generous spoon full of the whipped cream, using the back of a spoon make a little nest indentation in the top for the cherry filling.',
          ingredients: [
            {
              id: 1054,
              name: 'whipped cream',
              localizedName: 'whipped cream',
              image: 'whipped-cream.jpg',
            },
            {
              id: 9070,
              name: 'cherries',
              localizedName: 'cherries',
              image: 'cherries.jpg',
            },
          ],
          equipment: [],
        },
        {
          number: 14,
          step: "Add a spoon full of the cherry filling and you're done.",
          ingredients: [
            {
              id: 9070,
              name: 'cherries',
              localizedName: 'cherries',
              image: 'cherries.jpg',
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl:
    'https://spoonacular.com/black-forest-mini-cheesecakes-635113',
}

export default data
